name: "HiViSer - Action"
description: "HiViSer visualisations for your repository"
branding:
  icon: "search"
  color: "blue"

inputs:
  repository_path:
    description: >
      The root directory of the repository.
    default: "."
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    REPOSITORY_PATH: ${{ inputs.repository_path }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"