name: Generate HiViSer visualisations

on: [push]

permissions:
  contents: write

jobs:
  deploy:
    name: Deploy HiViSer GitHub Pages
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action, we must check out the repository
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup pnpm ⚙️
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Setup Node.js ⚙️
      uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install and Build 🔧
        run: |
          pnpm ci
          pnpm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
