name: Generate HiViSer visualisations

on: [push]

jobs:
  test:
    name: Run HiViSer Action
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      # To use this repository's private action,
      # we must check out the repository
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          path: "github-software-analytics-embedding"

      - name: Run HiViSer 🚀
        uses: ./ # Uses the action in the root directory
        with:
          repository_root: ./testrepo
